import { DependenceTreeNode } from '@/types/datadev';

export const data: DependenceTreeNode = {
  jobId: 1,
  jobName: 'root',
  jobStatus: 'waiting',
  lastRunTime: '2021-12-06 15:21:57',
  taskId: 1,
  nextLevel: 2,
  children: [
    {
      jobId: 2,
      jobName: 'prev',
      jobStatus: 'success',
      lastRunTime: '2021-12-06 15:21:57',
      taskId: 2,
      relation: 'prev',
      nextLevel: 3,
      children: [
        {
          jobId: 2,
          jobName: 'ads_yuntiads_yunti',
          jobStatus: 'running',
          lastRunTime: '2021-12-06 15:21:57',
          taskId: 2,
          relation: 'prev',
          nextLevel: 5,
          children: [
            {
              jobId: 2,
              jobName: 'ads_yunti',
              jobStatus: 'success',
              lastRunTime: '2021-12-06 15:21:57',
              taskId: 2,
              relation: 'prev',
              nextLevel: 3,
            },
            {
              jobId: 3,
              jobName: 'ads_yuntiads_yunti',
              jobStatus: 'fail',
              lastRunTime: '2021-12-06 15:21:57',
              taskId: 3,
              relation: 'prev',
            },
          ],
        },
        {
          jobId: 3,
          jobName: 'ads_yunti',
          jobStatus: 'fail',
          lastRunTime: '2021-12-06 15:21:57',
          taskId: 3,
          relation: 'prev',
        },
      ],
    },
    {
      jobId: 3,
      jobName: 'next1',
      jobStatus: 'others',
      lastRunTime: '2021-12-06 15:21:57',
      taskId: 3,
      relation: 'next',
      nextLevel: 3,
      children: [
        {
          jobId: 2,
          jobName: 'ads_yunti',
          jobStatus: 'running',
          lastRunTime: '2021-12-06 15:21:57',
          taskId: 2,
          relation: 'next',
        },
        {
          jobId: 3,
          jobName: 'ads_yunti',
          jobStatus: 'fail',
          lastRunTime: '2021-12-06 15:21:57',
          taskId: 3,
          relation: 'next',
        },
      ],
    },
    {
      jobId: 4,
      jobName: 'next2',
      jobStatus: 'success',
      lastRunTime: '2021-12-06 15:21:57',
      taskId: 4,
      relation: 'next',
    },
  ],
  prevLevel: 1,
};
