package cn.zhengcaiyun.idata.user.dal.model.auth;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table uac_auth_entry
 */
public class AuthEntry {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   是否删除，0否，1是
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.del")
    private Integer del;

    /**
     * Database Column Remarks:
     *   创建者
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.creator")
    private String creator;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.create_time")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改者
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.editor")
    private String editor;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.edit_time")
    private Date editTime;

    /**
     * Database Column Remarks:
     *   授权主体唯一标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.subject_id")
    private String subjectId;

    /**
     * Database Column Remarks:
     *   授权主体类型，users：用户，groups：用户组，apps：应用
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.subject_type")
    private String subjectType;

    /**
     * Database Column Remarks:
     *   备注
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.remark")
    private String remark;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.del")
    public Integer getDel() {
        return del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.del")
    public void setDel(Integer del) {
        this.del = del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.creator")
    public String getCreator() {
        return creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.creator")
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.editor")
    public String getEditor() {
        return editor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.editor")
    public void setEditor(String editor) {
        this.editor = editor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.edit_time")
    public Date getEditTime() {
        return editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.edit_time")
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.subject_id")
    public String getSubjectId() {
        return subjectId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.subject_id")
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.subject_type")
    public String getSubjectType() {
        return subjectType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.subject_type")
    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.remark")
    public String getRemark() {
        return remark;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: uac_auth_entry.remark")
    public void setRemark(String remark) {
        this.remark = remark;
    }
}