package cn.zhengcaiyun.idata.develop.dal.model.integration;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ite_ds_depend_relation
 */
public class DSDependRelation {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.create_time")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   ds工作流code
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.workflow_code")
    private Long workflowCode;

    /**
     * Database Column Remarks:
     *   ds任务节点code，depend_level是workflow时为0
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.task_code")
    private Long taskCode;

    /**
     * Database Column Remarks:
     *   上游ds工作流code，depend_level是task时为0
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.prev_workflow_code")
    private Long prevWorkflowCode;

    /**
     * Database Column Remarks:
     *   上游ds业务实体code，depend_level是workflow时为0
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.prev_task_code")
    private Long prevTaskCode;

    /**
     * Database Column Remarks:
     *   ds依赖节点code
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.depend_node_code")
    private Long dependNodeCode;

    /**
     * Database Column Remarks:
     *   依赖level: workflow, task
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.depend_level")
    private String dependLevel;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.workflow_code")
    public Long getWorkflowCode() {
        return workflowCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.workflow_code")
    public void setWorkflowCode(Long workflowCode) {
        this.workflowCode = workflowCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.task_code")
    public Long getTaskCode() {
        return taskCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.task_code")
    public void setTaskCode(Long taskCode) {
        this.taskCode = taskCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.prev_workflow_code")
    public Long getPrevWorkflowCode() {
        return prevWorkflowCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.prev_workflow_code")
    public void setPrevWorkflowCode(Long prevWorkflowCode) {
        this.prevWorkflowCode = prevWorkflowCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.prev_task_code")
    public Long getPrevTaskCode() {
        return prevTaskCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.prev_task_code")
    public void setPrevTaskCode(Long prevTaskCode) {
        this.prevTaskCode = prevTaskCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.depend_node_code")
    public Long getDependNodeCode() {
        return dependNodeCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.depend_node_code")
    public void setDependNodeCode(Long dependNodeCode) {
        this.dependNodeCode = dependNodeCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.depend_level")
    public String getDependLevel() {
        return dependLevel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ite_ds_depend_relation.depend_level")
    public void setDependLevel(String dependLevel) {
        this.dependLevel = dependLevel;
    }
}