package cn.zhengcaiyun.idata.develop.dal.model;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dev_job_udf
 */
public class DevJobUdf {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.del")
    private Integer del;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.creator")
    private String creator;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.editor")
    private String editor;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.create_time")
    private Date createTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.edit_time")
    private Date editTime;

    /**
     * Database Column Remarks:
     *   '函数名称'
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_name")
    private String udfName;

    /**
     * Database Column Remarks:
     *   函数类型
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_type")
    private String udfType;

    /**
     * Database Column Remarks:
     *   文件名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.file_name")
    private String fileName;

    /**
     * Database Column Remarks:
     *   hdfs文件路径
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.hdfs_path")
    private String hdfsPath;

    /**
     * Database Column Remarks:
     *   返回类型
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.return_type")
    private String returnType;

    /**
     * Database Column Remarks:
     *   返回值
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.return_sample")
    private String returnSample;

    /**
     * Database Column Remarks:
     *   目标文件夹
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.folder_id")
    private Long folderId;

    /**
     * Database Column Remarks:
     *   描述
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.description")
    private String description;

    /**
     * Database Column Remarks:
     *   命令格式
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.command_format")
    private String commandFormat;

    /**
     * Database Column Remarks:
     *   示例
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_sample")
    private String udfSample;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.del")
    public Integer getDel() {
        return del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.del")
    public void setDel(Integer del) {
        this.del = del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.creator")
    public String getCreator() {
        return creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.creator")
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.editor")
    public String getEditor() {
        return editor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.editor")
    public void setEditor(String editor) {
        this.editor = editor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.edit_time")
    public Date getEditTime() {
        return editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.edit_time")
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_name")
    public String getUdfName() {
        return udfName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_name")
    public void setUdfName(String udfName) {
        this.udfName = udfName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_type")
    public String getUdfType() {
        return udfType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_type")
    public void setUdfType(String udfType) {
        this.udfType = udfType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.file_name")
    public String getFileName() {
        return fileName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.file_name")
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.hdfs_path")
    public String getHdfsPath() {
        return hdfsPath;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.hdfs_path")
    public void setHdfsPath(String hdfsPath) {
        this.hdfsPath = hdfsPath;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.return_type")
    public String getReturnType() {
        return returnType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.return_type")
    public void setReturnType(String returnType) {
        this.returnType = returnType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.return_sample")
    public String getReturnSample() {
        return returnSample;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.return_sample")
    public void setReturnSample(String returnSample) {
        this.returnSample = returnSample;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.folder_id")
    public Long getFolderId() {
        return folderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.folder_id")
    public void setFolderId(Long folderId) {
        this.folderId = folderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.description")
    public String getDescription() {
        return description;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.description")
    public void setDescription(String description) {
        this.description = description;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.command_format")
    public String getCommandFormat() {
        return commandFormat;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.command_format")
    public void setCommandFormat(String commandFormat) {
        this.commandFormat = commandFormat;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_sample")
    public String getUdfSample() {
        return udfSample;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: dev_job_udf.udf_sample")
    public void setUdfSample(String udfSample) {
        this.udfSample = udfSample;
    }
}