package cn.zhengcaiyun.idata.system.dal.model;

import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   系统配置表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_config
 */
public class SysConfig {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   是否删除(1:是,其他:否)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.del")
    private Short del;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.create_time")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.edit_time")
    private Date editTime;

    /**
     * Database Column Remarks:
     *   系统配置键1
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.key_one")
    private String keyOne;

    /**
     * Database Column Remarks:
     *   系统配置值1
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.value_one")
    private String valueOne;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.del")
    public Short getDel() {
        return del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.del")
    public void setDel(Short del) {
        this.del = del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.edit_time")
    public Date getEditTime() {
        return editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.edit_time")
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.key_one")
    public String getKeyOne() {
        return keyOne;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.key_one")
    public void setKeyOne(String keyOne) {
        this.keyOne = keyOne;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.value_one")
    public String getValueOne() {
        return valueOne;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: sys_config.value_one")
    public void setValueOne(String valueOne) {
        this.valueOne = valueOne;
    }
}