package cn.zhengcaiyun.idata.system.dal.model;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table workspace
 */
public class Workspace {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.del")
    private Integer del;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.creator")
    private String creator;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.editor")
    private String editor;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.create_time")
    private Date createTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.edit_time")
    private Date editTime;

    /**
     * Database Column Remarks:
     *   工作空间名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.name")
    private String name;

    /**
     * Database Column Remarks:
     *   工作空间code
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.code")
    private String code;

    /**
     * Database Column Remarks:
     *   工作空间url path前缀
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.url_path")
    private String urlPath;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.del")
    public Integer getDel() {
        return del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.del")
    public void setDel(Integer del) {
        this.del = del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.creator")
    public String getCreator() {
        return creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.creator")
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.editor")
    public String getEditor() {
        return editor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.editor")
    public void setEditor(String editor) {
        this.editor = editor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.edit_time")
    public Date getEditTime() {
        return editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.edit_time")
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.name")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.code")
    public String getCode() {
        return code;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.code")
    public void setCode(String code) {
        this.code = code;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.url_path")
    public String getUrlPath() {
        return urlPath;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: workspace.url_path")
    public void setUrlPath(String urlPath) {
        this.urlPath = urlPath;
    }
}