POST http://localhost:9527/api/p1/ops/dashboard/page/jobHistory
Content-Type: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

{"pageNum":1,"pageSize":10,"condition":{"state":7}}

###
GET http://localhost:9527/api/p1/ops/dashboard/rank/resourceConsume?recentDays=7
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

### 资源消耗TOP 10
GET http://localhost:9527/api/p1/ops/dashboard/rank/timeConsume?recentDays=7
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

### 耗时TOP10
GET http://localhost:9527/api/p1/ops/dashboard/job/stackLine?scope=yarn
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

### YARN-折线图
POST http://localhost:9527/api/p1/ops/dashboard/page/yarn
Content-Type: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

{"pageNum":2,"pageSize":10,"condition":{"state":7}}

### 集群情况-详情
GET http://localhost:9527/api/p1/ops/dashboard/yarn/overview
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

### 集群情况
GET http://localhost:9527/api/p1/ops/dashboard/job/stackLine?scope=ds
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

### DS-折线图
POST http://localhost:9527/api/p1/ops/dashboard/page/jobSchedule
Content-Type: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

{"pageNum":1,"pageSize":10,"condition":{"state":6}}

### 调度情况-详情
GET http://localhost:9527/api/p1/ops/dashboard/jobSchedule/overview
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

### 调度情况
GET http://localhost:9527/api/p1/ops/dashboard/usageOverview
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; redirect=; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjUxLCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjM5NTMzMTM4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.apwo7nsFZC4I86IQ_OE1fQpntUrdnWUWyTcdg41brwbG3pKRdb80pFeD95tSt7iBw2ZhUL89VLFRl__B6kMSYw

### CPU使用情况
