GET http://localhost:8080/api/p0/job/execute-detail?jobId=2395&env=stag
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; _ga=GA1.2.1266048430.1640225432; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5Y2g5Lm-IiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjEyOCwiYXZhdGFyIjoiTlVMTCIsImV4cCI6MTY0ODgwNDQ2MiwiZW1haWwiOiJ6aGFucWlhbkBjYWktaW5jLmNvbSIsInVzZXJuYW1lIjoiemhhbnFpYW4ifQ.Ivj8ZM58a9HzZFuU0Eo_nSwlr3uy8UVJdsvyY-zLmALD4YWegrTgVBrV2m4ckD-hUwBSilWjcBMj2jsR2P0NOQ; redirect=http%3A%2F%2Fpaas-master.cai-inc.com%2Fdashboard%2Fops%2Fvessel%2Fapps%23%2Fvessel%2Fapps


###
GET http://localhost:8081/api/p1/sys/folderTree
Accept: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; _ga=GA1.2.1266048430.1640225432; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5YyX56yZIiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjE4LCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjQ4MDE1MjQ4LCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.W5IlI5rmYKpaEXca5ADG3AVTO_vOkDEBGJk2Hfp4Z6elJkqd7HHUO1J5FKgF1ljK-MHvpOOYXc9j302gDg-8_w

###
