POST http://localhost:9527/api/p1/ops/dashboard/page/gantt/jobHistory
Content-Type: application/json
Cookie: _zcy_log_client_uuid=53bfb4f0-45e6-11ec-9d71-57b6b6ff67b3; _ga=GA1.2.1266048430.1640225432; Authorization=eyJhbGciOiJIUzUxMiJ9.eyJyZWFsTmFtZSI6IuWNoOS5viIsIm5pY2tuYW1lIjoi5YyX56yZIiwibW9iaWxlIjoiMTg2NTc5NzA2ODUiLCJlbXBsb3llZUlkIjoiQzAxMDMzIiwiaWQiOjE4LCJhdmF0YXIiOiJOVUxMIiwiZXhwIjoxNjQwNjgzNzcxLCJlbWFpbCI6InpoYW5xaWFuQGNhaS1pbmMuY29tIiwidXNlcm5hbWUiOiJ6aGFucWlhbiJ9.QKy9epWtnit3zcJwvufLJBr2qqE0AMMzn4nQlDJz1ksIRa6FZvu1R0y-v5SKEKI8p2aRg_GzXl_f8p_DSyQnFw

{"pageSize":10,"pageNum":1,"condition":{}}

