package cn.zhengcaiyun.idata.label.dal.model;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table lab_object_label
 */
public class LabObjectLabel {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   是否删除，0否，1是
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.del")
    private Integer del;

    /**
     * Database Column Remarks:
     *   创建者
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.creator")
    private String creator;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.create_time")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改者
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.editor")
    private String editor;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.edit_time")
    private Date editTime;

    /**
     * Database Column Remarks:
     *   名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.name")
    private String name;

    /**
     * Database Column Remarks:
     *   英文名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.name_en")
    private String nameEn;

    /**
     * Database Column Remarks:
     *   主体类型
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.object_type")
    private String objectType;

    /**
     * Database Column Remarks:
     *   备注
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.remark")
    private String remark;

    /**
     * Database Column Remarks:
     *   版本
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.version")
    private Integer version;

    /**
     * Database Column Remarks:
     *   起源记录id，修改时指向第一次创建的记录id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.origin_id")
    private Long originId;

    /**
     * Database Column Remarks:
     *   文件夹id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.folder_id")
    private Long folderId;

    /**
     * Database Column Remarks:
     *   标签规则，json格式
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.rules")
    private String rules;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.del")
    public Integer getDel() {
        return del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.del")
    public void setDel(Integer del) {
        this.del = del;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.creator")
    public String getCreator() {
        return creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.creator")
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.editor")
    public String getEditor() {
        return editor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.editor")
    public void setEditor(String editor) {
        this.editor = editor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.edit_time")
    public Date getEditTime() {
        return editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.edit_time")
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.name")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.name_en")
    public String getNameEn() {
        return nameEn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.name_en")
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.object_type")
    public String getObjectType() {
        return objectType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.object_type")
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.remark")
    public String getRemark() {
        return remark;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.remark")
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.version")
    public Integer getVersion() {
        return version;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.version")
    public void setVersion(Integer version) {
        this.version = version;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.origin_id")
    public Long getOriginId() {
        return originId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.origin_id")
    public void setOriginId(Long originId) {
        this.originId = originId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.folder_id")
    public Long getFolderId() {
        return folderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.folder_id")
    public void setFolderId(Long folderId) {
        this.folderId = folderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.rules")
    public String getRules() {
        return rules;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: lab_object_label.rules")
    public void setRules(String rules) {
        this.rules = rules;
    }
}